const candidatesData = [
  {
    id: 1,
    firstName: "Anmol",
    lastName: "Mahajan",
    position: "Sr. Engineer",
    status: 2,
    reward: "2000",
  },
  {
    id: 2,
    firstName: "Tanmay",
    lastName: "Singh",
    position: "Frontend Engineer",
    status: 3,
    reward: "200",
  },
  {
    id: 3,
    firstName: "Anmol",
    lastName: "Singh",
    position: "Dev ops Engineer",
    status: 4,
    reward: "1000",
  },
  {
    id: 4,
    firstName: "Anamika",
    lastName: "Jain",
    position: "Jr. Engineer",
    status: 3,
    reward: "300",
  },
  {
    id: 5,
    firstName: "Lex",
    lastName: "Fridman",
    position: "AI Engineer",
    status: 4,
    reward: "2000",
  },
  {
    id: 6,
    firstName: "Carl",
    lastName: "Pie",
    position: "Product Engineer",
    status: 3,
    reward: "20000",
  },
  {
    id: 7,
    firstName: "Rahul",
    lastName: "Kumar",
    position: "Sr. Engineer",
    status: 2,
    reward: "1000",
  },
  {
    id: 8,
    firstName: "Ajay",
    lastName: "Bisht",
    position: "Backend Engineer",
    status: 4,
    reward: "200",
  },
];

export default candidatesData;
